### ISSUE TITLE
fa1.2 implementation

### ISSUE THREAD

**Issue by chiptus** [edukera/archetype-gitbook#6]
I'm going over your implementation for FA1.2 while trying to implement it myself. I think your implementation is not 100% with the specs and I would love to know how to fix it.

from [specs](https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-7/tzip-7.md):
> `UnsafeAllowanceChange` - attempt to change approval value from non-zero to non-zero was performed. The error will contain `nat :previous` value, where `previous` stands for the allowance value upon the contract call.

First, the implementation fails with "Unsafe Allowance Change" - should be one word. Second, how can I return the previous value? see https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-5/tzip-5.md#errors
 
Thanks!

**Comment by rognierbenoit** [comment]
Thanks for the feedback! There is currently no conversion from nat to string. we are fixing it and will let you know.

**Comment by chiptus** [comment]
I don't think theres a needed conversion, but a way to fail with a record, no?

**Comment by rognierbenoit** [comment]
Yes indeed your are right. We are rather going to allow any Michelson compliant type to be an argument of `fail`. 

Typically the approve entry will be something like : 
``` 
entry approve(spender : address, value : nat) {
  var k = (caller, spender);
  if allowance.contains(k) then (
    var previous = allowance[k].amount;
    if previous > 0 and value > 0
    then fail(("UnsafeAllowanceChange", previous)));
  allowance.addupdate( k, { amount = value });
}
```

**Comment by chiptus** [comment]
cool. is this planned for 1.2?

**Comment by rognierbenoit** [comment]
yes it should be available in typically 2 weeks time.

**Comment by chiptus** [comment]
thanks!

**Comment by rognierbenoit** [comment]
Hi Chiptus, version 1.1.1 is released and fixes it. you may opam upgrade archetype. 
Let us know if you have any comment and issue.
